
<div class="outerrel add-background" id="cstPrntId">
    <div class="wrapper container_16">

        <div class="add-container grid_16">
            <table width="100%" border="0">
                <?php
                if (isset($this->errors) && count($this->errors) > 0)
                {
                    ?>
                    <tr>
                        <td class="success" align="center">

                            <?
                            foreach ($this->errors as $error)
                            {
                                echo $error . "<br>";
                            }
                            ?>
                        </td>
                    </tr>

                    <?php
                }
                ?> 
            </table>
            <div class="add-holder">
                <span class="add-new dont-print-me">
                    <input class='btnAdd' style='margin-left:10px' value="" name="" type="button" onclick="javascript:document.location.href = '<?= BASE_URL_DASHBOARD . "admin/employeeadd" ?>'" />
                </span>

                <div class="clear"></div>

                <table class="main-grid" id="data_grid" width="100%" border="1">
                    <tr class="titles" >
                        <td class="no-right-border" width="20%">User</td>
                        <td width="20%">Email</td>       
                        <td width="20%">Role</td>       
                        <td width="20%">Modified Date/Time</td>  
                        <td width="20%" class="dont-print-me">Action</td>
                    </tr>
                    <?php
                    $i = 0;
                    if ($this->employees)
                    {
                        $rowclass = '';
                        foreach ($this->employees as $employee)
                        {

                            $rowclass = ($rowclass == '') ? 'lightblue' : '';
                            $role = $employee->getRole();
                            $rName='';
                            if($role)
                            {
                                $rName = $role->getName();
                            }
                           
                            ?>
                            <tr class="<?php echo $rowclass; ?>">
                                <td ><?php echo $employee->getFullName() ?></td>
                                <td ><?php echo $employee->getEmail() ?></td>
                                <td ><?php echo $rName ?></td>
                                <td><?php echo Application_Model_Helpers_Common::mysqlDateToLocal($employee->getModified(),TRUE) ?></td> 
                                <td class="dont-print-me">
        <?php if ($role->getId() != 2)
        { ?>
                                        <a href="<?= BASE_URL_DASHBOARD; ?>admin/employeeedit/id/<?php echo $employee->getId() ?>">Edit</a> / 
                                        <a href="javascript:void(0)" onclick="deleteEmployee('<?= BASE_URL_DASHBOARD; ?>admin/employeedelete/id/<?php echo $employee->getId() ?>')">Delete</a>
                                    <?php } ?>
                                </td>
                            </tr>
                            <?php
                            $i++;
                        }
                    }  
                    else
                    {
                    ?>
                            <tr>
                                <td colspan="5"> No Result Found.</td>
                            </tr>
                    <?php        
                    }
                    ?>
                </table>

            </div>
        </div>

        <div class="clear"></div>
         <div class="dont-print-me">
            <input type="button" onclick="customPrint($('#cstPrntId').html())" value=" " class="print-btn dont-print-me" style="float: right" />
        </div>

    </div>
</div>
