
<div class="outerrel add-background">
    <div class="wrapper container_16">

        <div class="add-container grid_16">
            <div class="profile signerarea-update-profile">


                <table width="100%" border="0">
                    <?php
                    if (isset($this->errors) && count($this->errors) > 0)
                    {
                        ?>
                        <tr>
                            <td colspan="3" class="error">

                                <?php
                                foreach ($this->errors as $error)
                                {
                                    echo $error . "<br>";
                                }
                                ?>
                            </td>
                        </tr>

                        <?php
                    }
                    ?> 
                </table>

                <form enctype="multipart/form-data" method="post" action="<?= BASE_URL_DASHBOARD; ?>admin/employeesave" name="empSave" onsubmit="return validEmployeeSave(this)">
                    <input type="hidden" name="id" value="<?php echo $this->id ?>">

                    <table width="100%" border="0" id="">

                        <tr>
                            <td colspan="2" >&nbsp;</td>                               
                        </tr>
                        <tr>
                            <td >&nbsp;</td>
                            <td >&nbsp;</td>
                        </tr>
                        <tr>
                            <td>First Name:</td>
                            <td><input class="tfield" name="fname" type="text" value="<?php echo $this->fname ?>"></td>
                            
                        </tr>  
                        <tr>
                            <td >&nbsp;</td>
                            <td >&nbsp;</td>
                        </tr>
                        <tr>
                            <td>Last Name:</td>
                            <td><input class="tfield" name="lname" type="text" value="<?php echo $this->lname ?>"></td>
                            
                        </tr>  
                        <tr>
                            <td >&nbsp;</td>
                            <td >&nbsp;</td>
                        </tr>
                        <tr>
                            <td>Email:</td>
                            <td><input class="tfield" name="email" type="text" value="<?php echo $this->email ?>"></td>
                            
                        </tr>
                        <?php
                        if($this->id == 0)
                        {
                        ?>
                            <tr>
                                <td >&nbsp;</td>
                                <td >&nbsp;</td>
                            </tr>
                            <tr>
                                <td>Password:</td>
                                <td><input class="tfield" name="password" type="password" value="<?php echo $this->password ?>"></td>

                            </tr>  
                        <?php
                        }
                        ?>
                        <tr>
                            <td >&nbsp;</td>
                            <td >&nbsp;</td>
                        </tr>
                        <tr>
                            <td>Role:</td>
                            <td>
                                <select name="roleId">
                                    <option value="">--Select Role--</option>
                                    <?php
                                    $checked='';
                                    if($this->roles)
                                    {
                                        
                                        foreach ($this->roles as $role)
                                        {
                                            $checked='';
                                            if($role->getId() == $this->roleId)
                                            {
                                                $checked='selected="selected"';
                                            }
                                    ?>
                                    <option <?php echo $checked?> value="<?php echo $role->getId()?>"><?php echo $role->getName()?></option>
                                    <?php
                                        }
                                    }
                                    ?>
                                </select>
                            </td>
                            
                        </tr>  
                        <tr>
                            <td >&nbsp;</td>
                            <td >&nbsp;</td>
                        </tr>
                      

                        <tr>
                            <td colspan="4">
                                <table width="100%" border="0">
                                    <tr>                          
                                        <td>
                                            <div align="right">
                                          
                                            <input class="cancel-b" name="cancel" type="button" value="" onclick="javascript:document.location.href='<?= BASE_URL_DASHBOARD."admin/employee"?>'" />
                                            </div>
                                            </td>
                                        <td colspan="2">&nbsp;</td>
                                        
                                        <td>
                                            <div align="left">
                                                <input class="btn-Save" name="submit" type="submit" value=" " />
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>

                </form>


                <div class="clear"></div>

            </div>
        </div>
    </div>
</div>