<div class="outerrel add-background">
    <div class="wrapper container_16">

        <div class="add-container grid_16">
            <table width="100%" border="0">
                <?php
                if (isset($this->errors) && count($this->errors) > 0)
                {
                    ?>
                    <tr>
                        <td class="success" align="center">

                            <?
                            foreach ($this->errors as $error)
                            {
                                echo $error . "<br>";
                            }
                            ?>
                        </td>
                    </tr>

                    <?php
                }
                ?> 
            </table>
            <div class="add-holder">
                <span class="add-new">
                    <input class='btnAdd' style='margin-left:10px' value="" name="" type="button" onclick="javascript:document.location.href = '<?= BASE_URL_DASHBOARD . "admin/resourcegroupadd" ?>'" />
                </span>

                <div class="clear"></div>

                <table class="main-grid" id="data_grid" width="100%" border="1">
                    <tr class="titles" >
                        <td class="no-right-border" width="20%">Name</td>
                        <td width="40%">Resources</td>       
                        <td width="20%">Modified Date/Time</td>       
                        <td width="10%">Status</td>
                        <td width="20%">Action</td>
                    </tr>
                    <?php
                    $i = 0;
                    if ($this->resgrp)
                    {
                        $rowclass = '';
                        foreach ($this->resgrp as $resgrp)
                        {

                            $rowclass = ($rowclass == '') ? 'lightblue' : '';
                            $resources = $resgrp->getResources();
                            $resName = "";
                            if ($resources)
                            {
                                foreach ($resources as $resource)
                                {
                                    $resName.=$resource->getName() . "<br>";
                                }
                            }
                            ?>
                            <tr class="<?php echo $rowclass; ?>">
                                <td ><?php echo $resgrp->getName() ?></td>
                                <td ><?php echo $resName ?></td>
                                <td><?php echo $resgrp->getModifiedOn() ?></td> 
                                <td ><?php echo $resgrp->getStatus() ?></td>
                                <td >
                                    <a href="<?= BASE_URL_DASHBOARD; ?>admin/resourcegroupedit/id/<?php echo $resgrp->getId() ?>">Edit</a> / 
                                    <a href="javascript:void(0)" onclick="deleteRole('<?= BASE_URL_DASHBOARD; ?>admin/resourcegroupdelete/id/<?php echo $resgrp->getId() ?>')">Delete</a>

                                </td>
                            </tr>
                            <?php
                            $i++;
                        }
                    }
                    ?>
                </table>

            </div>
        </div>

        <div class="clear"></div>

    </div>
</div>
