
<div class="outerrel add-background">
    <div class="wrapper container_16">

        <div class="add-container grid_16">
            <div class="profile signerarea-update-profile">


                <table width="100%" border="0">
                    <?php
                    if (isset($this->errors) && count($this->errors) > 0)
                    {
                        ?>
                        <tr>
                            <td colspan="3" class="error">

                                <?
                                foreach ($this->errors as $error)
                                {
                                    echo $error . "<br>";
                                }
                                ?>
                            </td>
                        </tr>

                        <?php
                    }
                    ?> 
                </table>

                <form enctype="multipart/form-data" method="post" action="<?= BASE_URL_DASHBOARD; ?>admin/rolesave" name="roleSave" onsubmit="return validRoleSave(this)">
                    <input type="hidden" name="id" value="<?php echo $this->id ?>">

                    <table width="100%" border="0" id="">

                        <tr>
                            <td colspan="2" >Add Role</td>                               
                        </tr>
                        <tr>
                            <td >&nbsp;</td>
                            <td >&nbsp;</td>
                        </tr>
                        <tr>
                            <td>Role Name:</td>
                            <td><input class="tfield" name="rname" type="text" value="<?php echo $this->roleName ?>"></td>
                            
                        </tr>  
                        <tr>
                            <td >&nbsp;</td>
                            <td >&nbsp;</td>
                        </tr>
                        <tr>
                            <td>Resource Groups:</td>
                            <td>
                                 <table width="100%" border="0">
                                    <?php
                                    if($this->res)
                                    {
                                        foreach ($this->res as $res)
                                        {
                                            $chk ='';
                                            if(in_array($res->getId(), $this->roleResArray))
                                            {
                                                $chk = ' checked="checked" ';
                                            }
                                            
                                    ?>
                                            <tr>                          
                                                <td width="5%"> <input type="checkbox" name="resources[]" value="<?php echo $res->getId() ?>" <?php echo $chk?> ></td>
                                                <td><?php echo $res->getName();?></td>
                                            </tr>
                                    <?php
                                        }
                                    }
                                    ?>
                                 </table>
                            </td>
                        </tr>                      


                        <tr>
                            <td colspan="4">
                                <table width="100%" border="0">
                                    <tr>                          
                                        <td>
                                            <div align="right">
                                          
                                            <input class="cancel-b" name="cancel" type="button" value="" onclick="javascript:document.location.href='<?= BASE_URL_DASHBOARD."admin/role"?>'" />
                                            </div>
                                            </td>
                                        <td colspan="2">&nbsp;</td>
                                        
                                        <td>
                                            <div align="left">
                                                <input class="btn-Save" name="submit" type="submit" value=" " />
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>

                </form>


                <div class="clear"></div>

            </div>
        </div>
    </div>
</div>