
<div class="outerrel add-background" id="cstPrntId">
    <div class="wrapper container_16">
        <?php echo $this->message();?>
        <div class="add-container grid_16">
           
            <div class="add-holder">
                <span class="add-new dont-print-me">
                    <input class='btnAdd' style='margin-left:10px' value="Add" name="" type="button" onclick="javascript:document.location.href = '<?php echo  BASE_URL_ADMIN . "/acl/useradd" ?>'" />
                </span>

                <div class="clear"></div>

                <table class="main-grid" id="data_grid" width="100%" border="1">
                    <tr class="titles" >
                        <td class="no-right-border" width="20%">User</td>
                        <td width="20%">Email</td>       
                        <td width="20%">Role</td>       
                        <td width="20%">Modified Date/Time</td>  
                        <td width="20%" class="dont-print-me">Action</td>
                    </tr>
                    <?php
                    $i = 0;
                    if ($this->users)
                    {
                        $rowclass = '';
                        foreach ($this->users as $user)
                        {

                            $rowclass = ($rowclass == '') ? 'lightblue' : '';
                            $role = $user->getRole();
                            $rName='';
                            if($role)
                            {
                                $rName = $role->getName();
                            }
                           
                            ?>
                            <tr class="<?php echo $rowclass; ?>">
                                <td ><?php echo $user->getFullName() ?></td>
                                <td ><?php echo $user->getEmail() ?></td>
                                <td ><?php echo $rName ?></td>
                                <td><?php echo Application_Model_Helpers_Common::mysqlDateToLocal($user->getModified(),TRUE) ?></td> 
                                <td class="dont-print-me">
        <?php if ($role->getId() != 2)
        { ?>
                                        <a href="<?php echo  BASE_URL_ADMIN; ?>/acl/useredit/id/<?php echo $user->getId() ?>">Edit</a> / 
                                        <a href="javascript:void(0)" onclick="deleteUser('<?php echo  BASE_URL_ADMIN; ?>/acl/userdelete/id/<?php echo $user->getId() ?>')">Delete</a>
                                    <?php } ?>
                                </td>
                            </tr>
                            <?php
                            $i++;
                        }
                    }  
                    else
                    {
                    ?>
                            <tr>
                                <td colspan="5"> No Result Found.</td>
                            </tr>
                    <?php        
                    }
                    ?>
                </table>

            </div>
        </div>

    </div>
</div>
