<?php
$sessionNameSpace = Zend_Registry::get('SESS_admin');
$user = $sessionNameSpace->user;

echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?>
        <meta name="generator" content="Bootply" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
            <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>/css/site.css" />  
            <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>/css/jquery/jquery-ui.css" />

            <script type="text/javascript" src="<?php echo BASE_URL; ?>/js/jquery/jquery-2.1.1.js" ></script>   
            <script type="text/javascript" src="<?php echo BASE_URL; ?>/js/jquery/jquery-ui.js" ></script>
            <script type="text/javascript" src="<?php echo BASE_URL; ?>/js/site.js" ></script>
            <script type="text/javascript" src="<?php echo BASE_URL; ?>/js/admin.js" ></script>    
    </head> 
    <body>


        <div id="dialog-custom-confirm" title="" style="display: none;"></div>
        <!-- Header -->
        <div id="top-nav" class="navbar navbar-inverse navbar-static-top" style="height: 50px;background-color: #D1F2F9">
            HEADER -- Aggregated Feed
            <div style="float: right">
                <?php
                if ($user instanceof Application_Model_User && $user->getId() > 0)
                {
                ?>
                    Well Come <?php echo $user->getFullName();?>
                    <a href="<?php echo $this->url(array('action' => 'logout', 'controller' => 'login')) ?>">LOG OUT</a>
                <?php 
                }
                ?>
            </div>
        </div>
        <!-- /Header --> 


        <div class="container">
            <?php
            if ($user instanceof Application_Model_User && $user->getId() > 0)
            {
                ?>
                <div class="col-mm-1 custom-menu navbar-collapse collapse">
                    <!-- Menu -->                   
                    <?php
                    $partial = array('menu.phtml', 'default');
                    $this->navigation()->menu()->setPartial($partial);
                    echo $this->navigation()->menu()->render();
                    ?>
                </div>
                <?php
            }
            ?>
            <br>
                <?php echo $this->layout()->content ?>
        </div>


    </body>
</html>