<?php if ($this->pageCount): 
    $params=Zend_Controller_Front::getInstance()->getRequest()->getParams();
    array_walk_recursive($params, 'Application_Model_Helpers_Common::urlEncode');     
    
    $fromdate = $this->fromdate;
    ?>
<div class="text-center">
    <ul class="pagination">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li><a href="<?php echo BASE_URL_ADMIN . '/feeddata/index/feedid/'.$this->feedid.'/?page='.$this->previous ?>">«</a></li>            
        <?php else: ?>
            <li><a href="#">«</a></li>
        <?php endif; ?>
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>           
                <li><a href="<?php echo BASE_URL_ADMIN . '/feeddata/index/feedid/'.$this->feedid.'/?page='.$page ?>"><?php echo $page; ?></a></li>                
            <?php else: ?>                
                <li><a href="#" style="background-color:#D1F2F9"><?php echo $page; ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>            
            <li><a href="<?php echo BASE_URL_ADMIN . '/feeddata/index/feedid/'.$this->feedid.'/?page='.$this->next ?>">»</a></li>
        <?php else: ?>
            <li><a href="#">»</a></li>
        <?php endif; ?>
    </ul>
</div>
<?php endif; ?>


