<?php echo $this->message(); ?>
<form action="<?php
echo $this->url(array(
    'action' => 'auth'
));
?>" enctype="application/x-www-form-urlencoded" method="post" class="form-signin" onsubmit="return checkValidation();">


    <div class="list-group">
        <div class="form-group input-group email">
            <span class="input-group-addon fa fa-envelope-o"></span>
            <input type="text" name="username" class="form-control" placeholder="Email Address" required>
        </div>

        <div class="form-group input-group password">
            <span class="input-group-addon fa fa-lock"></span>
            <input type="password" name="password"  class="form-control" placeholder="Password" required>
        </div>
        <!--<label class="checkbox">
            <input type="checkbox" name="remember_me" value="remember-me"> Remember me                
        </label>-->
    </div>

    <button class="btn btn-lg btn-primary btn-block login" name="btnSubmit" type="submit">Login In</button>

</form>
