<style>
    table.sorting-table {cursor: move;}
    table tr.sorting-row td {background-color: #8b8;}
    table td.sorter {background-color: #f80; width: 10px; cursor: move;}
    table tr.nodrag td.sorter {cursor: default; background-color: #ddd;}
    .sort-handler {float: right; background-color: #f80; width: 14px; height: 14px; margin: 2px 0 0 6px; cursor: move;}
</style>
<?php echo $this->message(); ?>

<div class="row page-title">
    <div class="col-md-12">
        <button class="btn btn-lg btn-primary pull-right" onclick="javascript:document.location.href = '<?php echo BASE_URL_ADMIN . "/index" ?>'">Back</button>
      
        <h1 class="pull-left"><?php echo $this->feedName ?></h1>

    </div><!-- /.col-md-8 -->

    <div class="clearfix"></div>
</div><!-- / page title -->
<div class="col-lg-12">
    <div class="table-responsive reorder-feed">
        <table class="table table-bordered table-striped" id="reorder-feed-table">
            <thead>
                <tr>
                    <th>Feed Data</th>
<!--                    <th>Order</th>-->

                </tr>
            </thead>
            <tbody>

                <?php
                if ($this->feeddata)
                {
                    $rowclass = '';
                    foreach ($this->feeddata as $data)
                    {
                        ?>
                        <tr>
                            <td <?php echo ($data->getHide() == 1)?'style="background-color: pink"':'' ?> >
                               <a href="#" style="float:right" class="link-hide" feedId="<?php 
                                        echo $data->getId() ?>"><?php 
                                            echo ($data->getHide() == 0)?'<i class="fa fa-eye" style="font-size: xx-large" title="Hide"></i>':'<i class="fa fa-eye-slash" style="font-size: xx-large" title="Show"></i >';
                                        ?></a>                                
                                <a href="<?php echo $data->getLink() ?>" target="_blank"><?php echo $data->getTitle() ?></a>
                                <p class="date"><?php echo Application_Model_Helpers_Common::mysqlDateToLocal($data->getPublishDate(), 1) ?></p>
                                  <p><?php echo  $data->getDescription()  ?> </p>
                            </td>
                            <!--<td class="action"><a href="#"><i class="fa fa-eye"></i ><i class="fa fa-arrow-up"></i ></a></td>-->
                        </tr>
                        <?php
                    }
                }
                ?>



            </tbody>
        </table>
    </div><!-- / responsive table  -->
</div>

<script>

    $("#tab-sort-feed").rowSorter({
        onDrop: function (tbody, row, index, oldIndex) {
            alert((oldIndex + 1) + ". row moved to " + (index + 1));
        }
    });
    
     $(".link-hide").click(function(){    
            var id = $(this).attr('feedId');
            var fromdate = $('#fromdate').val();
            document.location.href = '<?php echo BASE_URL_ADMIN ?>/feeddata/togglehide/id/'+id+'/feedid/'+<?php echo $this->feedid ?>
    });

</script>