
<style>
    table.sorting-table {cursor: move;}
    table tr.sorting-row td {background-color: #8b8;}
    table td.sorter {background-color: #f80; width: 10px; cursor: move;}
    table tr.nodrag td.sorter {cursor: default; background-color: #ddd;}
    .sort-handler {float: right; background-color: #f80; width: 14px; height: 14px; margin: 2px 0 0 6px; cursor: move;}
</style>
<?php echo $this->message(); ?>

<div class="row page-title">
    <div class="col-md-12">
        <button class="btn btn-lg btn-primary pull-right" onclick="javascript:document.location.href = '<?php echo BASE_URL_ADMIN . "/index" ?>'">Back</button>
        <button class="btn btn-lg btn-primary pull-right" onclick="javascript:document.location.href = '<?php echo BASE_URL_ADMIN . "/feeddata/refreshfeed" ?>'">Refresh</button>
        <h1 class="pull-left">Reorder Feed </h1>

    </div><!-- /.col-md-8 -->

    <div class="clearfix"></div>
</div><!-- / page title -->
<div class="col-lg-12">
    <div class="table-responsive reorder-feed">
        <form id="frm" name="frm" method="GET" >
            <table>
                <tr>
                    <td>From Date:<input type="text" id="fromdate" name="fromdate" value="<?php echo $this->fromdate ?>" /></td>
                    <td></td>
                    <td>To Date:<input type="text" id="todate" name="todate" value="<?php echo $this->todate ?>" readonly="true" /></td>
                    <td></td>
                    <td><input type="submit" id="submit" value="Filter"  class="btn btn-lg btn-primary pull-right" /> </td>
                </tr>
            </table>
        </form>
        <table class="table table-bordered table-striped" id="reorder-feed-table">
            <thead>
                <tr>
                    <th>Feed Data</th>


                </tr>
            </thead>
            <tbody>

                <?php
                if ($this->feeddata)
                {
                    $rowclass = '';
                    foreach ($this->feeddata as $data)
                    {
                        ?>
                <tr fdid="<?php echo $data->getId() ?>">
                            <td>
                                <a href="<?php echo $data->getLink() ?>" target="_blank"><?php echo $data->getTitle() ?></a>
                                <p class="date"><?php echo Application_Model_Helpers_Common::mysqlDateToLocal($data->getPublishDate(), 1) ?></p>

                                            </td>

                                        </tr>
                                <?php
                            }
                }
                ?>



            </tbody>
        </table>
    </div><!-- / responsive table  -->
</div>

<script>

    $("#reorder-feed-table").rowSorter({
        onDrop: function (tbody, row, index, oldIndex) {
            //alert((oldIndex + 1) + ". row moved to " + (index + 1));
            
            var prevRow = tbody.getElementsByTagName("tr")[index - 1];
            var nextRow = tbody.getElementsByTagName("tr")[index + 1];
            
            var betweenFromId = 0;
            var betweenToId = 0;
            var id = row.getAttribute("fdid");
            
            if(prevRow)
            {
               betweenFromId =  prevRow.getAttribute("fdid");
            }
            if(nextRow)
            {
               betweenToId =  nextRow.getAttribute("fdid");
            }
            
            var fromdate = $('#fromdate').val();
            
            
            javascript:document.location.href = '<?php echo BASE_URL_ADMIN ?>/feeddata/feeddataorder/id/' + id + '/betweenFromId/' + betweenFromId + '/betweenToId/' + betweenToId+"/fromdate/"+fromdate;
        }
    });

    var options = {
        dateFormat: $('#fromdate').attr('dateFormat')?$('#fromdate').attr('dateFormat'):"yy-mm-dd",
        changeMonth: true,
        changeYear: true,
        minDate: $('#fromdate').attr('minDate'),
        maxDate: $('#fromdate').attr('maxDate')

    };
     $('#fromdate').datepicker( options);
     $("#fromdate").datepicker( "option", "maxDate", $('#todate').val() );
</script>
