<style>
    table.sorting-table {cursor: move;}
    table tr.sorting-row td {background-color: #8b8;}
    table td.sorter {background-color: #f80; width: 10px; cursor: move;}
    table tr.nodrag td.sorter {cursor: default; background-color: #ddd;}
    .sort-handler {float: right; background-color: #f80; width: 14px; height: 14px; margin: 2px 0 0 6px; cursor: move;}
</style>
<?php echo $this->message(); ?>

<div class="row page-title">
    <div class="col-md-12">
        <button class="btn btn-lg btn-primary pull-right" onclick="javascript:document.location.href = '<?php echo BASE_URL_ADMIN . "/index" ?>'">Back</button>
        <button class="btn btn-lg btn-primary pull-right" onclick="javascript:document.location.href = '<?php echo BASE_URL_ADMIN . "/feeddata/refreshfeed" ?>'">Refresh</button>
        <h1 class="pull-left">Reorder Feed </h1>

    </div><!-- /.col-md-8 -->

    <div class="clearfix"></div>
</div><!-- / page title -->
<div class="col-lg-12">
    <div class="table-responsive reorder-feed">
        <table class="table table-bordered table-striped" id="reorder-feed-table">
            <thead>
                <tr>
                    <th>Feed Data</th>


                </tr>
            </thead>
            <tbody>

                <?php
                if ($this->feeddata)
                {
                    $rowclass = '';
                    foreach ($this->feeddata as $data)
                    {
                        ?>
                <tr fdid="<?php echo $data->getId() ?>">
                            <td>
                                <a href="<?php echo $data->getLink() ?>" target="_blank"><?php echo $data->getTitle() ?></a>
                                <p class="date"><?php echo Application_Model_Helpers_Common::mysqlDateToLocal($data->getPublishDate(), 1) ?></p>
                                 
                                    </td>
                           
                        </tr>
                        <?php
                    }
                }
                ?>



            </tbody>
        </table>
    </div><!-- / responsive table  -->
</div>

<script>

    $("#reorder-feed-table").rowSorter({
        onDrop: function (tbody, row, index, oldIndex) {
            alert((oldIndex + 1) + ". row moved to " + (index + 1));
            //javascript:document.location.href = '<?php echo BASE_URL_ADMIN ?>/feeddata/feeddataorder/id/' + row.getAttribute("fdid") + '/oldIndex/' + (oldIndex + 1) + '/newIndex/' + (index + 1);
        }
    });

</script>
